taskMng1/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <pluralLabel>Tasks</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Task Name</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <label>Completed</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>
</CustomObject>

taskMng1/force-app/main/default/objects/Task__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <label>Completed</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

taskMng1/force-app/main/default/objects/Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

taskMng1/force-app/main/default/classes/TaskController.cls
public with sharing class TaskController {
    
    @AuraEnabled(cacheable=true)
    public static List<Task__c> getTasks() {
        return [SELECT Id, Name, Due_Date__c, Completed__c FROM Task__c];
    }
    //Enabling aura for the lwc
    @AuraEnabled
    public static void markTaskComplete(Id taskId) {
        Task__c task = [SELECT Id, Completed__c FROM Task__c WHERE Id = :taskId LIMIT 1];
        task.Completed__c = true;
        update task;
    }
}