taskMng1/force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <pluralLabel>Tasks</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Task Name</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <label>Completed</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>
</CustomObject>

taskMng1/force-app/main/default/objects/Task__c/fields/Completed__c.field-meta.xml
<CustomField>
    <fullName>Completed__c</fullName>
    <label>Completed</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

taskMng1/force-app/main/default/objects/Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

taskMng1/force-app/main/default/classes/TaskBatchJob.cls
public class TaskBatchJob implements Database.Batchable<sObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id FROM Task__c WHERE Due_Date__c < TODAY AND Completed__c = false'
        );
    }

    public void execute(Database.BatchableContext bc, List<Task__c> scope) {
        for (Task__c task : scope) {
            task.Completed__c = true;
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('Batch job completed successfully.');
    }
}